#!/bin/sh
#
# x360_daemon        Starts x360_daemon.
#

start() {
	echo -n "Starting x360_daemon: "
	/bin/x360_daemon
	echo "OK"
}
stop() {
	echo -n "Stopping x360_daemon: "
	killall x360_daemon
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

