#!/bin/sh
#
# httpd        Starts httpd.
#

start() {
	echo -n "Starting httpd: "
	httpd -h /var/www
	echo "OK"
}
stop() {
	echo -n "Stopping sshd: "
	killall httpd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

